[2023-01-08 09:05:29,133] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:05:26.153387+00:00 [queued]>
[2023-01-08 09:05:29,138] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:05:26.153387+00:00 [queued]>
[2023-01-08 09:05:29,138] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:05:29,138] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-08 09:05:29,138] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:05:29,153] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): building_db_test> on 2023-01-08 09:05:26.153387+00:00
[2023-01-08 09:05:29,157] {standard_task_runner.py:52} INFO - Started process 5271 to run task
[2023-01-08 09:05:29,163] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'building_db_test', 'manual__2023-01-08T09:05:26.153387+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/lead_scoring_data_pipeline_test.py', '--cfg-path', '/tmp/tmpyzzhv_no', '--error-file', '/tmp/tmpngxd_y8c']
[2023-01-08 09:05:29,164] {standard_task_runner.py:80} INFO - Job 52: Subtask building_db_test
[2023-01-08 09:05:29,208] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:05:26.153387+00:00 [running]> on host 1f037b111ba5
[2023-01-08 09:05:29,252] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=building_db_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T09:05:26.153387+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T09:05:26.153387+00:00
[2023-01-08 09:05:29,253] {logging_mixin.py:115} INFO - DBPath/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils_output.db
[2023-01-08 09:05:29,253] {logging_mixin.py:115} INFO - DB Already Exsist
[2023-01-08 09:05:29,314] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:200 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:05:29,318] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:209 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:05:29,321] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:218 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:05:29,415] {logging_mixin.py:115} INFO - df.shape[0] :100
[2023-01-08 09:05:29,415] {logging_mixin.py:115} INFO - df_test.shape[0] :100
[2023-01-08 09:05:29,415] {python.py:173} INFO - Done. Returned value was: None
[2023-01-08 09:05:29,421] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=building_db_test, execution_date=20230108T090526, start_date=20230108T090529, end_date=20230108T090529
[2023-01-08 09:05:29,452] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-08 09:05:29,482] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
